// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqphgmpaoadhurhqcrmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xcGhnbXBhb2FkaHVyaHFjcm14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MDY2NjQsImV4cCI6MjA2OTk4MjY2NH0.5SilrCtAqel6m7Q_agfi1hICvRvF1z4F6rf0fle-eGQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});